server:
  port: 8080

spring:
  datasource:
    url: ${DB_NAME}
    username: ${DB_UN}
    password: ${DB_PW}

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update

  jwt:
    key: ${JWT_KEY}
    access: ${JWT_AC}
    refresh: ${JWT_RF}

cloud:
  aws:
    s3:
      default-image: ${S3_DF}
      url: ${S3_URL}
      bucket: ${S3_BK}
    credentials:
      access-key: ${AWS_AC}
      secret-key: ${AWS_SC}
    region:
      static: ${AWS_RG}
    stack:
      auto: false

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    org:
      hibernate:
        type: trace