name: xquare-deployment

on:
  push:
    branches: [ "main" ]

jobs:
  job-name:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Deploy to xquare
        uses: team-xquare/xquare-deployment-action@master
        with:
          environment: prod
          access_key: ${{ secrets.XQUARE_ACCESS_KEY }}
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          buildargs: |
            DB_NAME=${{ secrets.DB_NAME }}
            DB_UN=${{ secrets.DB_UN }}
            DB_PW=${{ secrets.DB_PW }}
            JWT_KEY=${{ secrets.JWT_KEY }}
            JWT_AC=${{ secrets.JWT_AC }}
            JWT_RF=${{ secrets.JWT_RF }}
            S3_DF=${{ secrets.S3_DF }}
            S3_BK=${{ secrets.S3_BK }}
            S3_URL=${{ secrets.S3_URL }}
            AWS_AC=${{ secrets.AWS_AC }}
            AWS_RG=${{ secrets.AWS_RG }}
            AWS_SC=${{ secrets.AWS_SC }}
            
            
            
            